l# A Sample Java Web-Application
:experimental:

image:https://travis-ci.org/st-tu-dresden/guestbook.svg?branch=master["Build Status", link="https://travis-ci.org/st-tu-dresden/guestbook"]

Purpose of this sample project is to make students familiar with basic technologies they're going to use during the Software Engineering Lab at Technical University of Dresden.

## Quickstart

NOTE: The Quickstart requires Java 11, and a recent Git (2.21 or better preferred) to be available on your machine. If you miss any of those go through the steps described in <<prerequisites>>.
Also, note that you have to run `mvnw.bat` instead of `mvnw` if you run Windows by accident.

[source, shell]
----
$ git clone https://github.com/st-tu-dresden/guestbook
$ cd guestbook
$ mvnw clean package
$ mvnw spring-boot:run
----

After that point your browser to `http://localhost:8080`.

## Prerequisites

### Java 11

https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html[Download] the binaries, install. Make sure the console shows something like this:

[source, bash]
----
$ java -version
openjdk version "11.0.2" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.2+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7, mixed mode)
----

### Git

http://git-scm.com/download[Download] the binaries, run the installer. Verify the command line shows something like this after install:

[source, bash]
----
$ git --version
git version 2.21.0
----

## IDE Setup

Grab the latest https://spring.io/tools/sts/all[STS] (Spring Tool Suite, plain Eclipse Luna or IntelliJ should work as well), run installer or unzip and run it.

Select menu:File[Import], select menu:Maven[Existing Maven Projects], select the folder you checked the project out into and hit btn:[Finish]. This will import the project into your workspace.

In the Console view you might wanna click the btn:[Open Console] button and select Maven Console to see that Maven is downloading dependencies, sources and Javadocs.

## Technology stack

This sample application is build on top of the following technologies:

### Spring Boot

Rapid application development framework based on Spring (see below).

- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle[Reference documentation]
- https://spring.io/guides[Getting started guides]
- https://projects.spring.io/spring-boot[Project home]

### Spring Framework

The de-facto standard Java application framework.

- https://spring.io/guides[Getting started guides]
- https://projects.spring.io/spring-framework[Project home]

### Spring Data JPA

Spring module to easily build data acess layers using JPA 2.2 (Java Persistence API).

- https://spring.io/guides?filter=jpa[Getting started guides]
- https://projects.spring.io/spring-data-jpa[Project home]

### Thymeleaf

Library to build HTML web views using natural templating.

- https://spring.io/guides/gs/serving-web-content[Getting stared guide]
- https://www.thymeleaf.org/doc/usingthymeleaf.html[Tutorial]
